[package]
name = "exe7"
version = "0.1.0"
authors = ["shiweixxx <swxxxa@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[lib]
name = "structs"
path = "src/structs.rs"
test = true
